dynamically get distribution id

diff --git a/.github/workflows/on-merge.yml b/.github/workflows/on-merge.yml
--- a/.github/workflows/on-merge.yml
+++ b/.github/workflows/on-merge.yml
@@ -46,8 +46,18 @@ jobs:
       - name: Sync webserver build to S3
         run: aws s3 sync ./build s3://chatter-webserver
 
+      - name: Find Cloudfront distribution id
+        id: get-id
+        run: |
+          DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items[?contains(@, 'chitchatter.link')]].Id | [0]" --output text)
+          if [ -z "$DISTRIBUTION_ID" ]; then
+            echo "Error: No CloudFront distribution ID found. Exiting with failure."
+            exit 1
+          fi
+          echo "::set-output name=distribution-id::$DISTRIBUTION_ID"
+
       - name: Invalidate CloudFront cache
-        run: aws cloudfront create-invalidation --distribution-id EQEEM8QWW3YFX --paths "/*"
+        run: aws cloudfront create-invalidation --distribution-id ${{ steps.get-id.outputs.distribution-id }} --paths "/*"
 
       - name: Run Integration Tests
         uses: cypress-io/github-action@v6
